In [1]:
import pandas as pd
from NC import importNC

In [3]:
프레임목록=importNC('./data/')

In [5]:
안타13=프레임목록[0]['안타']
안타14=프레임목록[1]['안타']
안타15=프레임목록[2]['안타']

시즌안타=pd.concat([안타13, 안타14, 안타15], axis=1)
시즌안타

         안타     안타     안타
강구성     0.0    NaN    1.0
강민국     NaN    0.0    0.0
강진성     1.0    NaN    NaN
권희동     NaN   63.0    NaN
김동건     2.0    NaN    NaN
김성욱     1.0    4.0    NaN
김종찬     1.0    NaN    NaN
김종호   129.0    NaN  125.0
김준완     NaN    2.0   10.0
김태군     NaN    NaN  107.0
김태우     NaN    1.0    NaN
김태진     NaN    NaN    0.0
나성범    98.0  157.0  184.0
노진혁     NaN    3.0    NaN
마낙길     9.0    0.0    NaN
모창민   109.0  110.0   62.0
박명환*    NaN    0.0    NaN
박민우    11.0  124.0  158.0
박정준    41.0    NaN    8.0
손시헌     NaN   90.0  108.0
용덕한     NaN    NaN   12.0
이상호    31.0    NaN    NaN
이승호     0.0    NaN    NaN
이종욱     NaN  126.0  118.0
이창섭     0.0    NaN    0.0
이현곤    38.0    NaN    NaN
이호준   123.0  115.0  132.0
조영훈   107.0   29.0   35.0
조평호    21.0    0.0    8.0
지석훈    68.0   58.0  111.0
차화준    24.0    NaN    NaN
최재원     NaN    0.0   21.0
테임즈     NaN  152.0  180.0
허준      NaN    5.0    NaN

In [6]:
def 최대최소값구하기(시리즈):
    return 시리즈.max() - 시리즈.min()

In [13]:
시즌안타.apply(최대최소값구하기)
# apply : 함수를 인자로 받아서 적용하는 함수

안타    129.0
안타    157.0
안타    184.0
dtype: float64

각 색인별로 함수 적용

In [9]:
시즌안타.apply(최대최소값구하기, axis=1)

강구성       1.0
강민국       0.0
강진성       0.0
권희동       0.0
김동건       0.0
김성욱       3.0
김종찬       0.0
김종호       4.0
김준완       8.0
김태군       0.0
김태우       0.0
김태진       0.0
나성범      86.0
노진혁       0.0
마낙길       9.0
모창민      48.0
박명환*      0.0
박민우     147.0
박정준      33.0
손시헌      18.0
용덕한       0.0
이상호       0.0
이승호       0.0
이종욱       8.0
이창섭       0.0
이현곤       0.0
이호준      17.0
조영훈      78.0
조평호      21.0
지석훈      53.0
차화준       0.0
최재원      21.0
테임즈      28.0
허준        0.0
dtype: float64

In [16]:
NC15=프레임목록[-1]
# 목록 제일 뒤에 있는 것을 불러옴

In [15]:
타율15=NC15['안타'] / NC15['타석']
타율15

선수명
테임즈    0.302521
나성범    0.295820
박민우    0.256078
이호준    0.254826
김종호    0.257202
조영훈    0.239726
손시헌    0.212598
이종욱    0.234127
모창민    0.259414
지석훈    0.238197
용덕한    0.244898
최재원    0.205882
박정준    0.333333
김태군    0.225738
조평호    0.363636
이창섭    0.000000
김준완    0.185185
강구성    0.200000
강민국    0.000000
김태진    0.000000
dtype: float64

In [17]:
def 소수점표현(값):
    값 = '{0:.2f}'.format(값)
    return 값

소수점표현(3.1415)

'3.14'

시리즈의 각 값에 함수를 적용

In [18]:
타율15.map(소수점표현)

선수명
테임즈    0.30
나성범    0.30
박민우    0.26
이호준    0.25
김종호    0.26
조영훈    0.24
손시헌    0.21
이종욱    0.23
모창민    0.26
지석훈    0.24
용덕한    0.24
최재원    0.21
박정준    0.33
김태군    0.23
조평호    0.36
이창섭    0.00
김준완    0.19
강구성    0.20
강민국    0.00
김태진    0.00
dtype: object

In [19]:
타율13=프레임목록[0]['안타'] / 프레임목록[0]['타석']
타율14=프레임목록[1]['안타'] / 프레임목록[1]['타석']
타율15=프레임목록[2]['안타'] / 프레임목록[2]['타석']

타율13.name=2013
타율14.name=2014
타율15.name=2015

시즌타율=pd.concat([타율13, 타율14, 타율15], axis=1)
시즌타율

          2013      2014      2015
강구성   0.000000       NaN  0.200000
강민국        NaN  0.000000  0.000000
강진성   0.333333       NaN       NaN
권희동        NaN  0.250000       NaN
김동건   0.117647       NaN       NaN
김성욱   0.250000  0.153846       NaN
김종찬   0.142857       NaN       NaN
김종호   0.236264       NaN  0.257202
김준완        NaN  0.400000  0.185185
김태군        NaN       NaN  0.225738
김태우        NaN  0.200000       NaN
김태진        NaN       NaN  0.000000
나성범   0.213974  0.292910  0.295820
노진혁        NaN  0.187500       NaN
마낙길   0.290323  0.000000       NaN
모창민   0.250000  0.235043  0.259414
박명환*       NaN  0.000000       NaN
박민우   0.229167  0.252546  0.256078
박정준   0.210256       NaN  0.333333
손시헌        NaN  0.249307  0.212598
용덕한        NaN       NaN  0.244898
이상호   0.224638       NaN       NaN
이승호   0.000000       NaN       NaN
이종욱        NaN  0.254545  0.234127
이창섭   0.000000       NaN  0.000000
이현곤   0.236025       NaN       NaN
이호준   0.242126  0.230000  0.254826
조영훈   0.251174  0.233871  0.239726
조평호   0.244186  0.000000  0.363636
지석훈   0.191011  0.243697  0.238197
차화준   0.198347       NaN       NaN
최재원        NaN  0.000000  0.205882
테임즈        NaN  0.295720  0.302521
허준         NaN  0.138889       NaN

* .apply : 열 또는 행 단위로 함수 적용
* .applymap : 각각의 값에 대해 함수 적용

In [20]:
시즌타율.applymap(소수점표현)

      2013  2014  2015
강구성   0.00   nan  0.20
강민국    nan  0.00  0.00
강진성   0.33   nan   nan
권희동    nan  0.25   nan
김동건   0.12   nan   nan
김성욱   0.25  0.15   nan
김종찬   0.14   nan   nan
김종호   0.24   nan  0.26
김준완    nan  0.40  0.19
김태군    nan   nan  0.23
김태우    nan  0.20   nan
김태진    nan   nan  0.00
나성범   0.21  0.29  0.30
노진혁    nan  0.19   nan
마낙길   0.29  0.00   nan
모창민   0.25  0.24  0.26
박명환*   nan  0.00   nan
박민우   0.23  0.25  0.26
박정준   0.21   nan  0.33
손시헌    nan  0.25  0.21
용덕한    nan   nan  0.24
이상호   0.22   nan   nan
이승호   0.00   nan   nan
이종욱    nan  0.25  0.23
이창섭   0.00   nan  0.00
이현곤   0.24   nan   nan
이호준   0.24  0.23  0.25
조영훈   0.25  0.23  0.24
조평호   0.24  0.00  0.36
지석훈   0.19  0.24  0.24
차화준   0.20   nan   nan
최재원    nan  0.00  0.21
테임즈    nan  0.30  0.30
허준     nan  0.14   nan