## 산술연산과 데이터 정렬

In [1]:
import pandas as pd

경로가 일정한 패턴을 가지고 있다면 문자열 양식을 사용하시는 것을 권장합니다.

In [2]:
경로='./data/NC Dinos {}.xlsx'

경로를 패턴으로 표현하면 여러 개의 파일을 읽어들여 데이터프레임으로 생성하는 것도 반복문으로 자동화할 수 있습니다. 두세 개는 직접 입력하는 거소가 큰 차이가 없지만, 그 이상의 개수는 자동화하는 것이 거의 언제나 바람직합니다.

In [5]:
#NC13=pd.read_excel(경로.format(2013))
#NC14=pd.read_excel(경로.format(2014))
#NC15=pd.read_excel(경로.format(2015))

In [12]:
프레임목록 = []
for 연도 in range(2013, 2016):
    프레임=pd.read_excel(경로.format(연도))
    프레임['시즌'] = 연도
    프레임=프레임.set_index('선수명')
    프레임목록.append(프레임)

In [13]:
프레임목록[2][:5]

,팀명,경기,타석,타수,안타,홈런,득점,타점,볼넷,삼진,도루,BABIP,타율,출루율,장타율,OPS,wOBA,WAR,시즌
선수명,,,,,,,,,,,,,,,,,,,
테임즈,NC,142,595,472,180,47,130,140,103,91,40,0.390,0.381,0.497,0.790,1.287,0.520,11.73,2015
나성범,NC,144,622,564,184,28,112,135,33,127,23,0.374,0.326,0.373,0.553,0.926,0.390,4.46,2015
박민우,NC,141,617,520,158,3,111,47,73,108,46,0.373,0.304,0.399,0.404,0.803,0.364,3.52,2015
이호준,NC,131,518,449,132,24,48,110,61,102,0,0.332,0.294,0.381,0.510,0.891,0.381,2.19,2015
김종호,NC,133,486,424,125,4,90,36,44,65,41,0.338,0.295,0.364,0.394,0.758,0.340,1.03,2015

In [14]:
안타13=프레임목록[0]['안타']
안타14=프레임목록[1]['안타']
안타15=프레임목록[2]['안타']

In [15]:
안타13[:3]

선수명
모창민    109
이호준    123
김종호    129
Name: 안타, dtype: int64

#### 연습
3년 간 시즌 안타 기록에서 각 선수별 누적 안타 합계를 구하고자 합니다. 
1. Excel 에서 수행
2. Pandas 에서 수행

사칙연산 수행 시, 위치와 상관없이 색인을 기준으로 수행됩니다.

In [20]:
안타13+안타14

선수명
강구성       NaN
강민국       NaN
강진성       NaN
권희동       NaN
김동건       NaN
김성욱       5.0
김종찬       NaN
김종호       NaN
김준완       NaN
김태우       NaN
나성범     255.0
노진혁       NaN
마낙길       9.0
모창민     219.0
박명환*      NaN
박민우     135.0
박정준       NaN
손시헌       NaN
이상호       NaN
이승호       NaN
이종욱       NaN
이창섭       NaN
이현곤       NaN
이호준     238.0
조영훈     136.0
조평호      21.0
지석훈     126.0
차화준       NaN
최재원       NaN
테임즈       NaN
허준        NaN
Name: 안타, dtype: float64

시즌안타, 홈런 누적 합계
1. 그냥 __+__ 연산을 하게 될 경우 NaN 값 연산으로 인해 한시즌이라도 데이터가 없으면 NaN으로 표기됨
2. __.add(...., fill_value=0)__ 으로 계산

In [23]:
열목록=['안타', '홈런']
# 프레임목록[0][열목록]+프레임목록[1][열목록]
프레임목록[0][열목록].add(프레임목록[1][열목록], fill_value=0)

         안타    홈런
선수명
강구성     0.0   0.0
강민국     0.0   0.0
강진성     1.0   0.0
권희동    63.0   7.0
김동건     2.0   1.0
김성욱     5.0   1.0
김종찬     1.0   0.0
김종호   129.0   0.0
김준완     2.0   0.0
김태우     1.0   0.0
나성범   255.0  44.0
노진혁     3.0   1.0
마낙길     9.0   0.0
모창민   219.0  28.0
박명환*    0.0   0.0
박민우   135.0   1.0
박정준    41.0   4.0
손시헌    90.0   5.0
이상호    31.0   0.0
이승호     0.0   0.0
이종욱   126.0   6.0
이창섭     0.0   0.0
이현곤    38.0   0.0
이호준   238.0  43.0
조영훈   136.0  12.0
조평호    21.0   2.0
지석훈   126.0   9.0
차화준    24.0   1.0
최재원     0.0   0.0
테임즈   152.0  37.0
허준      5.0   0.0

In [26]:
데이터=pd.concat([안타13, 안타14, 안타15], axis=1)
데이터.sum(axis=1)

강구성       1.0
강민국       0.0
강진성       1.0
권희동      63.0
김동건       2.0
김성욱       5.0
김종찬       1.0
김종호     254.0
김준완      12.0
김태군     107.0
김태우       1.0
김태진       0.0
나성범     439.0
노진혁       3.0
마낙길       9.0
모창민     281.0
박명환*      0.0
박민우     293.0
박정준      49.0
손시헌     198.0
용덕한      12.0
이상호      31.0
이승호       0.0
이종욱     244.0
이창섭       0.0
이현곤      38.0
이호준     370.0
조영훈     171.0
조평호      29.0
지석훈     237.0
차화준      24.0
최재원      21.0
테임즈     332.0
허준        5.0
dtype: float64

In [28]:
프레임목록[0][열목록].add(프레임목록[1][열목록], fill_value=0)

         안타    홈런
선수명
강구성     0.0   0.0
강민국     0.0   0.0
강진성     1.0   0.0
권희동    63.0   7.0
김동건     2.0   1.0
김성욱     5.0   1.0
김종찬     1.0   0.0
김종호   129.0   0.0
김준완     2.0   0.0
김태우     1.0   0.0
나성범   255.0  44.0
노진혁     3.0   1.0
마낙길     9.0   0.0
모창민   219.0  28.0
박명환*    0.0   0.0
박민우   135.0   1.0
박정준    41.0   4.0
손시헌    90.0   5.0
이상호    31.0   0.0
이승호     0.0   0.0
이종욱   126.0   6.0
이창섭     0.0   0.0
이현곤    38.0   0.0
이호준   238.0  43.0
조영훈   136.0  12.0
조평호    21.0   2.0
지석훈   126.0   9.0
차화준    24.0   1.0
최재원     0.0   0.0
테임즈   152.0  37.0
허준      5.0   0.0

## DataFrame 과 Series 간의 연산

In [30]:
NC15=프레임목록[2][열목록]
NC15

      안타  홈런
선수명
테임즈  180  47
나성범  184  28
박민우  158   3
이호준  132  24
김종호  125   4
조영훈   35   8
손시헌  108  13
이종욱  118   5
모창민   62   6
지석훈  111  11
용덕한   12   0
최재원   21   2
박정준    8   0
김태군  107   6
조평호    8   1
이창섭    0   0
김준완   10   0
강구성    1   0
강민국    0   0
김태진    0   0

안타와 홈런 합계에서 안타와 홈런이 각각 차지하는 비율을 구하고 싶다면?
1. 안타홈런합계 산출
2. 비율 산출

In [31]:
안타홈런합계=NC15['안타']+NC15['홈런']
안타홈런합계

선수명
테임즈    227
나성범    212
박민우    161
이호준    156
김종호    129
조영훈     43
손시헌    121
이종욱    123
모창민     68
지석훈    122
용덕한     12
최재원     23
박정준      8
김태군    113
조평호      9
이창섭      0
김준완     10
강구성      1
강민국      0
김태진      0
dtype: int64

In [34]:
NC15['안타'] / 안타홈런합계

선수명
테임즈    0.792952
나성범    0.867925
박민우    0.981366
이호준    0.846154
김종호    0.968992
조영훈    0.813953
손시헌    0.892562
이종욱    0.959350
모창민    0.911765
지석훈    0.909836
용덕한    1.000000
최재원    0.913043
박정준    1.000000
김태군    0.946903
조평호    0.888889
이창섭         NaN
김준완    1.000000
강구성    1.000000
강민국         NaN
김태진         NaN
dtype: float64

In [35]:
프레임=NC15.ix[:4, ['안타', '홈런']]
프레임

      안타  홈런
선수명
테임즈  180  47
나성범  184  28
박민우  158   3
이호준  132  24

안타와 홈런 기록이 집계 시점으 오류로 다섯 개씩 더 기록되고, 홈런은 3개씩 덜 기록되었다. 안타와 홈런의 기록을 정정한다.

In [36]:
기록정정=pd.Series({'안타':-5, '홈런':3})

In [37]:
기록정정[:3]

안타   -5
홈런    3
dtype: int64

In [38]:
프레임 + 기록정정

      안타  홈런
선수명
테임즈  175  50
나성범  179  31
박민우  153   6
이호준  127  27

In [39]:
테나=pd.Series({'테임즈':5, '나성범':3})
테나

나성범    3
테임즈    5
dtype: int64

In [40]:
프레임.ix[['테임즈', '나성범']].add(테나, axis=0)

      안타  홈런
나성범  187  31
테임즈  185  52

#### 연습
2015년 NC 타자들의 타율을 구한다. 타율은 안타홈런 합계를 타석으로 나눈 것이다.

In [57]:
NC15=프레임목록[2][['타석', '안타', '홈런']]

In [59]:
#NC15안타홈런=(NC15['안타'] + NC15['홈런']) / NC15['타석']
NC15안타홈런=NC15['안타'].add(NC15['홈런'], fill_value=0)
NC15안타홈런=NC15안타홈런.div(NC15['타석'])
NC15['타율']=NC15안타홈런

/Users/Koon/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [60]:
NC15

      타석   안타  홈런        타율
선수명
테임즈  595  180  47  0.381513
나성범  622  184  28  0.340836
박민우  617  158   3  0.260940
이호준  518  132  24  0.301158
김종호  486  125   4  0.265432
조영훈  146   35   8  0.294521
손시헌  508  108  13  0.238189
이종욱  504  118   5  0.244048
모창민  239   62   6  0.284519
지석훈  466  111  11  0.261803
용덕한   49   12   0  0.244898
최재원  102   21   2  0.225490
박정준   24    8   0  0.333333
김태군  474  107   6  0.238397
조평호   22    8   1  0.409091
이창섭    8    0   0  0.000000
김준완   54   10   0  0.185185
강구성    5    1   0  0.200000
강민국    2    0   0  0.000000
김태진    3    0   0  0.000000