In [99]:
import pandas as pd
from NC import importNC

from pandas_datareader import data, wb
from os.path import join

In [21]:
프레임목록 = importNC('./data/')

In [24]:
NC시즌 = pd.concat(프레임목록)
# 새로 방향으로 합치도록 설정

In [28]:
#선수명과 함께 시즌도 색인이 되도록 설정
#NC시즌.set_index('시즌', append=True)
NC시즌 = NC시즌.reset_index().set_index(['시즌', '선수명'])

In [30]:
NC시즌.ix[2015, '나성범']

팀명          NC
경기         144
타석         622
타수         564
안타         184
홈런          28
득점         112
타점         135
볼넷          33
삼진         127
도루          23
BABIP    0.374
타율       0.326
출루율      0.373
장타율      0.553
OPS      0.926
wOBA      0.39
WAR       4.46
Name: (2015, 나성범), dtype: object

In [49]:
NC시즌.ix[NC시즌[2013:2014].ix['나성범']]

KeyError: '나성범'

In [52]:
NC시즌.swaplevel('시즌', '선수명').unstack().stack()

           팀명     경기     타석     타수     안타    홈런     득점     타점     볼넷     삼진  \
선수명  시즌
강구성  2013  NC    2.0    2.0    2.0    0.0   0.0    0.0    0.0    0.0    0.0
     2015  NC    4.0    5.0    5.0    1.0   0.0    0.0    0.0    0.0    0.0
강민국  2014  NC    6.0    3.0    3.0    0.0   0.0    0.0    0.0    0.0    0.0
     2015  NC    1.0    2.0    2.0    0.0   0.0    0.0    0.0    0.0    1.0
강진성  2013  NC    3.0    3.0    2.0    1.0   0.0    1.0    0.0    1.0    0.0
권희동  2014  NC  101.0  252.0  221.0   63.0   7.0   39.0   36.0   25.0   43.0
김동건  2013  NC    7.0   17.0   16.0    2.0   1.0    1.0    1.0    1.0    7.0
김성욱  2013  NC    4.0    4.0    4.0    1.0   0.0    0.0    1.0    0.0    2.0
     2014  NC   26.0   26.0   23.0    4.0   1.0    6.0    1.0    3.0    9.0
김종찬  2013  NC    5.0    7.0    7.0    1.0   0.0    0.0    0.0    0.0    3.0
김종호  2013  NC  128.0  546.0  465.0  129.0   0.0   72.0   22.0   57.0  100.0
     2015  NC  133.0  486.0  424.0  125.0   4.0   90.0   36.0   44.0   65.0
김준완  2014  NC    6.0    5.0    4.0    2.0   0.0    1.0    0.0    1.0    1.0
     2015  NC   30.0   54.0   44.0   10.0   0.0   12.0    2.0   10.0   10.0
김태군  2015  NC  144.0  474.0  421.0  107.0   6.0   45.0   52.0   25.0   77.0
김태우  2014  NC    4.0    5.0    5.0    1.0   0.0    0.0    0.0    0.0    3.0
김태진  2015  NC    1.0    3.0    3.0    0.0   0.0    0.0    0.0    0.0    0.0
나성범  2013  NC  104.0  458.0  404.0   98.0  14.0   55.0   64.0   33.0   95.0
     2014  NC  123.0  536.0  477.0  157.0  30.0   88.0  101.0   43.0  128.0
     2015  NC  144.0  622.0  564.0  184.0  28.0  112.0  135.0   33.0  127.0
노진혁  2014  NC   25.0   16.0   16.0    3.0   1.0    3.0    2.0    0.0    7.0
마낙길  2013  NC   24.0   31.0   29.0    9.0   0.0    5.0    0.0    1.0    5.0
     2014  NC    2.0    2.0    1.0    0.0   0.0    1.0    0.0    1.0    0.0
모창민  2013  NC  108.0  436.0  395.0  109.0  12.0   57.0   51.0   37.0   68.0
     2014  NC  122.0  468.0  419.0  110.0  16.0   62.0   72.0   37.0   82.0
     2015  NC  103.0  239.0  214.0   62.0   6.0   23.0   35.0   18.0   52.0
박명환* 2014  NC    2.0    1.0    1.0    0.0   0.0    0.0    0.0    0.0    1.0
박민우  2013  NC   32.0   48.0   42.0   11.0   0.0   10.0    6.0    5.0    7.0
     2014  NC  118.0  491.0  416.0  124.0   1.0   87.0   40.0   56.0   89.0
     2015  NC  141.0  617.0  520.0  158.0   3.0  111.0   47.0   73.0  108.0
박정준  2013  NC   77.0  195.0  167.0   41.0   4.0   24.0   21.0   23.0   44.0
     2015  NC   19.0   24.0   21.0    8.0   0.0    2.0    2.0    0.0    5.0
손시헌  2014  NC   97.0  361.0  307.0   90.0   5.0   39.0   39.0   34.0   53.0
     2015  NC  140.0  508.0  440.0  108.0  13.0   56.0   58.0   36.0   66.0
용덕한  2015  NC   50.0   49.0   42.0   12.0   0.0    4.0    5.0    5.0    8.0
이상호  2013  NC  102.0  138.0  125.0   31.0   0.0   26.0   13.0    9.0   21.0
이승호  2013  NC    2.0    1.0    0.0    0.0   0.0    0.0    0.0    1.0    0.0
이종욱  2014  NC  124.0  495.0  438.0  126.0   6.0   73.0   79.0   40.0   60.0
     2015  NC  125.0  504.0  440.0  118.0   5.0   63.0   52.0   54.0   78.0
이창섭  2013  NC    5.0    5.0    5.0    0.0   0.0    0.0    0.0    0.0    2.0
     2015  NC   15.0    8.0    5.0    0.0   0.0    0.0    0.0    3.0    3.0
이현곤  2013  NC   91.0  161.0  139.0   38.0   0.0   10.0    9.0   16.0   14.0
이호준  2013  NC  126.0  508.0  442.0  123.0  20.0   46.0   87.0   60.0  109.0
     2014  NC  122.0  500.0  424.0  115.0  23.0   59.0   78.0   67.0  104.0
     2015  NC  131.0  518.0  449.0  132.0  24.0   48.0  110.0   61.0  102.0
조영훈  2013  NC  120.0  426.0  380.0  107.0   6.0   38.0   39.0   39.0   56.0
     2014  NC   92.0  124.0  111.0   29.0   6.0   15.0   22.0   10.0   26.0
     2015  NC  103.0  146.0  124.0   35.0   8.0   20.0   35.0   19.0   36.0
조평호  2013  NC   26.0   86.0   79.0   21.0   2.0   12.0    7.0    6.0   24.0
     2014  NC    2.0    2.0    2.0    0.0   0.0    0.0    0.0    0.0    0.0
     2015  NC   22.0   22.0   22.0    8.0   1.0    4.0    3.0    0.0    6.0
지석훈  2013  NC  104.0  356.0  309.0   68.0   3.0   25.0   35.0   30.0   82.0
     2014  NC  114.0  238.0  212.0   58.0   6.0   26.0   34.0   16.0   46.0
     2015  NC  137.0  466.0  415.0  111.0  11.0   53.0   46.0   23.0   85.0
차화준  2013  NC   58.0  121.0  106.0   24.0   1.0   18.0    7.0   12.0   29.0
최재원  2014  NC    2.0    2.0    1.0    0.0   0.0    1.0    0.0    1.0    1.0
     2015  NC  114.0  102.0   85.0   21.0   2.0   31.0   13.0   10.0   29.0
테임즈  2014  NC  125.0  514.0  443.0  152.0  37.0   95.0  121.0   58.0   99.0
     2015  NC  142.0  595.0  472.0  180.0  47.0  130.0  140.0  103.0   91.0
허준   2014  NC   28.0   36.0   29.0    5.0   0.0    2.0    1.0    5.0   10.0

             도루  BABIP     타율    출루율    장타율    OPS   wOBA    WAR
선수명  시즌
강구성  2013   0.0  0.000  0.000  0.000  0.000  0.000  0.000  -0.06
     2015   0.0    0.2    0.2  0.200    0.4    0.6  0.242  -0.04
강민국  2014   0.0  0.000      0  0.000      0      0  0.000  -0.10
     2015   0.0      0      0  0.000      0      0  0.000  -0.06
강진성  2013   0.0  0.500  0.500  0.667  1.000  1.667  0.671   0.10
권희동  2014   6.0  0.324  0.285  0.363  0.443  0.806  0.353   0.62
김동건  2013   0.0  0.125  0.125  0.176  0.313  0.489  0.216  -0.14
김성욱  2013   0.0  0.500  0.250  0.250  0.250  0.500  0.234  -0.03
     2014   1.0  0.231  0.174  0.269  0.348  0.617  0.272  -0.15
김종찬  2013   0.0  0.250  0.143  0.143  0.143  0.286  0.134  -0.11
김종호  2013  50.0  0.352  0.277  0.376  0.333  0.709  0.339   1.55
     2015  41.0  0.338  0.295  0.364  0.394  0.758  0.340   1.03
김준완  2014   1.0  0.667    0.5  0.600    0.5    1.1  0.509   0.11
     2015   2.0  0.294  0.227  0.370  0.227  0.597  0.308  -0.04
김태군  2015   1.0  0.293  0.254  0.307  0.354  0.661  0.294   0.25
김태우  2014   0.0  0.500    0.2  0.200    0.4    0.6  0.244  -0.03
김태진  2015   0.0      0      0  0.000      0      0  0.000  -0.09
나성범  2013  12.0  0.279  0.243  0.319  0.416  0.735  0.329   1.50
     2014  14.0  0.397  0.329  0.400  0.597  0.997  0.424   5.94
     2015  23.0  0.374  0.326  0.373  0.553  0.926  0.390   4.46
노진혁  2014   0.0  0.250  0.188  0.188  0.375  0.563  0.231  -0.18
마낙길  2013   2.0  0.375  0.310  0.333  0.345  0.678  0.317  -0.03
     2014   0.0  0.000      0  0.500      0    0.5  0.363   0.01
모창민  2013  16.0  0.307  0.276  0.339  0.443  0.782  0.353   2.31
     2014  14.0  0.289  0.263  0.320  0.413  0.733  0.319   0.17
     2015   5.0  0.352   0.29  0.340  0.439  0.779  0.340   0.76
박명환* 2014   0.0      -      0  0.000      0      0  0.000  -0.03
박민우  2013   9.0  0.306  0.262  0.333  0.286  0.619  0.296   0.07
     2014  50.0  0.373  0.298  0.392  0.399  0.791  0.365   2.73
     2015  46.0  0.373  0.304  0.399  0.404  0.803  0.364   3.52
박정준  2013   4.0  0.303  0.246  0.335  0.353  0.688  0.320   0.06
     2015   0.0    0.5  0.381  0.458  0.476  0.934  0.417   0.25
손시헌  2014   2.0  0.331  0.293  0.368  0.414  0.782  0.349   1.52
     2015   3.0   0.26  0.245  0.319  0.398  0.717  0.316   0.85
용덕한  2015   2.0  0.353  0.286  0.375   0.31  0.685  0.326   0.44
이상호  2013  24.0  0.298  0.248  0.299  0.320  0.619  0.289   0.16
이승호  2013   1.0      -      -  1.000      -      -  0.712   0.06
이종욱  2014  15.0  0.313  0.288  0.343  0.411  0.754  0.332   0.13
     2015  17.0  0.315  0.268  0.351  0.368  0.719  0.322   0.84
이창섭  2013   0.0  0.000  0.000  0.000  0.000  0.000  0.000  -0.14
     2015   0.0      0      0  0.375      0  0.375  0.286  -0.01
이현곤  2013   2.0  0.304  0.273  0.361  0.324  0.685  0.327   0.52
이호준  2013   2.0  0.324  0.278  0.362  0.475  0.837  0.373   1.85
     2014   2.0  0.305  0.271  0.371  0.481  0.852  0.369   0.88
     2015   0.0  0.332  0.294  0.381   0.51  0.891  0.381   2.19
조영훈  2013   4.0  0.316  0.282  0.350  0.413  0.763  0.348   0.83
     2014   1.0  0.288  0.261  0.325  0.459  0.784  0.337  -0.02
     2015   3.0  0.329  0.282  0.372   0.54  0.912  0.389   1.00
조평호  2013   1.0  0.358  0.266  0.318  0.418  0.736  0.329   0.09
     2014   0.0  0.000      0  0.000      0      0  0.000  -0.07
     2015   0.0  0.467  0.364  0.364  0.591  0.955  0.401   0.18
지석훈  2013   2.0  0.285  0.220  0.300  0.330  0.630  0.293  -0.09
     2014   1.0  0.323  0.274  0.340  0.462  0.802  0.352   0.97
     2015   4.0  0.311  0.267  0.328  0.383  0.711  0.317   0.51
차화준  2013   4.0  0.295  0.226  0.306  0.311  0.617  0.289  -0.12
최재원  2014   0.0      -      0  0.500      0    0.5  0.363   0.01
     2015  14.0  0.352  0.247  0.366  0.412  0.778  0.350   0.30
테임즈  2014  11.0  0.367  0.343  0.422  0.688   1.11  0.456   6.36
     2015  40.0   0.39  0.381  0.497   0.79  1.287  0.520  11.73
허준   2014   0.0  0.263  0.172  0.294  0.276   0.57  0.268  -0.11

#### 연습
날씨 데이터프레임에 대해 다음을 수행
1. location과 weekDay를 색인으로 설정
2. 서울날씨와 수원날씨를 1에서 색인이 설정된 데이터에서 각각 선택
3. 서울, 금요일 날씨만 선택

In [53]:
날씨 = pd.read_excel('./data/weather.xlsx')

In [57]:
날씨2 = 날씨.set_index(['location', 'weekDay'])

In [92]:
날씨2.ix['seoul'][:5]
# 지역이 색인으로 설정되었기 때문에 그냥 선택하면 됨

,date,avgTemp,highestTemp,lowestTemp,precipitation,snow,windSpeed,humidity,cloud,dayTime,weather
weekDay,,,,,,,,,,,
thur,2013-08-01,28.0,32.1,24.5,-,-,1.8,66,7.1,6.0,구름많음
fri,2013-08-02,27.4,29.3,25.2,7.5,-,2.1,79,9.1,0.9,흐림/안개/비
sat,2013-08-03,28.9,32.6,26.7,0.1,-,3.6,72,8.1,8.9,흐림/소나기
sun,2013-08-04,28.3,31.3,26.4,4.5,-,2.5,76,8.0,4.7,흐림/소나기/안개
mon,2013-08-05,27.7,30.1,26.4,7,-,3.3,78,7.0,4.5,구름많음/안개/천둥번개/비

In [96]:
날씨2.ix['seoul'].ix['fri'][:5]
# ix[색인조건, 열조건]

,date,avgTemp,highestTemp,lowestTemp,precipitation,snow,windSpeed,humidity,cloud,dayTime,weather
weekDay,,,,,,,,,,,
fri,2013-08-02,27.4,29.3,25.2,7.5,-,2.1,79,9.1,0.9,흐림/안개/비
fri,2013-08-09,29.2,30.8,27.9,0,-,4.0,79,9.9,0.1,흐림/안개
fri,2013-08-16,28.7,31.7,26.1,4.5,-,3.8,71,7.5,7.2,구름많음/소나기
fri,2013-08-23,25.7,28.7,23.7,35,-,2.4,78,8.2,1.0,흐림/안개/비
fri,2013-08-30,25.1,28.3,22.3,-,-,3.4,69,5.1,10.7,구름많음

### 재색인
나성범 선수의 모든 시즌 기록
안쪽에 있는 특정 색인의 값을 기준으로 선택을 수행할 때 사용됩니다.

In [97]:
NC시즌.reindex(['나성범','테임즈'], level=1)

          팀명   경기   타석   타수   안타  홈런   득점   타점   볼넷   삼진  도루  BABIP     타율  \
시즌   선수명
2013 나성범  NC  104  458  404   98  14   55   64   33   95  12  0.279  0.243
2014 나성범  NC  123  536  477  157  30   88  101   43  128  14  0.397  0.329
     테임즈  NC  125  514  443  152  37   95  121   58   99  11  0.367  0.343
2015 나성범  NC  144  622  564  184  28  112  135   33  127  23  0.374  0.326
     테임즈  NC  142  595  472  180  47  130  140  103   91  40   0.39  0.381

            출루율    장타율    OPS   wOBA    WAR
시즌   선수명
2013 나성범  0.319  0.416  0.735  0.329   1.50
2014 나성범  0.400  0.597  0.997  0.424   5.94
     테임즈  0.422  0.688   1.11  0.456   6.36
2015 나성범  0.373  0.553  0.926  0.390   4.46
     테임즈  0.497   0.79  1.287  0.520  11.73

재색인 기능이 없거나, 활용법을 모른다면 색인의 구조를 바꿔가면서 작업을 수행해야 합니다.

In [98]:
NC시즌.swaplevel('시즌', '선수명').ix[['나성범', '테임즈']].swaplevel('시즌', '선수명')

,,팀명,경기,타석,타수,안타,홈런,득점,타점,볼넷,삼진,도루,BABIP,타율,출루율,장타율,OPS,wOBA,WAR
시즌,선수명,,,,,,,,,,,,,,,,,,
2013,나성범,NC,104,458,404,98,14,55,64,33,95,12,0.279,0.243,0.319,0.416,0.735,0.329,1.50
2014,나성범,NC,123,536,477,157,30,88,101,43,128,14,0.397,0.329,0.400,0.597,0.997,0.424,5.94
2015,나성범,NC,144,622,564,184,28,112,135,33,127,23,0.374,0.326,0.373,0.553,0.926,0.390,4.46
2014,테임즈,NC,125,514,443,152,37,95,121,58,99,11,0.367,0.343,0.422,0.688,1.11,0.456,6.36
2015,테임즈,NC,142,595,472,180,47,130,140,103,91,40,0.39,0.381,0.497,0.79,1.287,0.520,11.73

#### 연습
식당 자료에 대해 다음을 수행

1. corner, dine_type을 색인으로 설정
2. dine_type에서 저녁 시간에 해당하는 자료만 선택

In [103]:
식당=pd.read_excel('./data/food_order.xlsx')

In [102]:
식당[:5]

,date,dine_type,corner,menu,is_sold_out,use_count,pred_count,additional,good,ok,bad,diff_use_pred,year,month,day,wday
0,2013-08-06,dinner,grill & fry,훈제연어벤또(200개),F,213,0,0,0,0,0,-213,2013,8,6,1
1,2013-08-06,dinner,rice & soup 1,뚝배기 우거지 갈비탕,F,261,0,0,0,0,0,-261,2013,8,6,1
2,2013-08-06,lunch,noodle bar,판모밀정식,F,267,0,0,0,0,0,-267,2013,8,6,1
3,2013-08-06,breakfast,rice & soup 1,설렁탕정식,F,1,0,0,0,0,0,-1,2013,8,6,1
4,2013-08-06,lunch,rice & soup 1,A. 부대찌개정식,F,376,0,0,0,0,0,-376,2013,8,6,1

In [105]:
식당 = 식당.set_index(['corner', 'dine_type'])

In [117]:
식당.reindex(['dinner'], level=1)

ValueError: cannot reindex from a duplicate axis

In [114]:
식당[:5]

                              date          menu is_sold_out  use_count  \
corner        dine_type
grill & fry   dinner    2013-08-06  훈제연어벤또(200개)           F        213
rice & soup 1 dinner    2013-08-06   뚝배기 우거지 갈비탕           F        261
noodle bar    lunch     2013-08-06         판모밀정식           F        267
rice & soup 1 breakfast 2013-08-06         설렁탕정식           F          1
              lunch     2013-08-06     A. 부대찌개정식           F        376

                         pred_count  additional  good  ok  bad  diff_use_pred  \
corner        dine_type
grill & fry   dinner              0           0     0   0    0           -213
rice & soup 1 dinner              0           0     0   0    0           -261
noodle bar    lunch               0           0     0   0    0           -267
rice & soup 1 breakfast           0           0     0   0    0             -1
              lunch               0           0     0   0    0           -376

                         year  month  day  wday
corner        dine_type
grill & fry   dinner     2013      8    6     1
rice & soup 1 dinner     2013      8    6     1
noodle bar    lunch      2013      8    6     1
rice & soup 1 breakfast  2013      8    6     1
              lunch      2013      8    6     1

데이터의 특성상 특정 형식으로 색인을 설정했을 때 .reindex가 실패할 수도 있습니다. 이 때는 계측 색인을 직접 조작해서 해야 합니다.

In [120]:
식당.swaplevel('corner', 'dine_type').ix['dinner']

,date,menu,is_sold_out,use_count,pred_count,additional,good,ok,bad,diff_use_pred,year,month,day,wday
corner,,,,,,,,,,,,,,
grill & fry,2013-08-06,훈제연어벤또(200개),F,213,0,0,0,0,0,-213,2013,8,6,1
rice & soup 1,2013-08-06,뚝배기 우거지 갈비탕,F,261,0,0,0,0,0,-261,2013,8,6,1
noodle bar,2013-08-12,차슈라멘,F,179,0,0,0,0,0,-179,2013,8,12,0
rice & soup 1,2013-08-12,김치날치알밥,F,216,0,0,0,0,0,-216,2013,8,12,0
grill & fry,2013-08-12,그릴드함박정식,F,336,0,0,0,0,0,-336,2013,8,12,0
rice & soup 1,2013-08-13,분차덮밥,F,457,0,0,0,0,0,-457,2013,8,13,1
noodle bar,2013-08-13,열무물냉면,F,136,0,0,0,0,0,-136,2013,8,13,1
burger&pizza,2013-08-13,오곡버거,F,115,0,0,0,0,0,-115,2013,8,13,1
grill & fry,2013-08-14,치킨데리야끼스테이크,F,229,0,0,0,0,0,-229,2013,8,14,2
rice & soup 1,2013-08-14,훈제오리&부추생채,F,280,0,0,0,0,0,-280,2013,8,14,2
after school,2013-08-14,라면세트,F,114,0,0,0,0,0,-114,2013,8,14,2
rice & soup 1,2013-08-19,삼겹살김치찜,F,441,0,0,0,0,0,-441,2013,8,19,0
after school,2013-08-19,라면+롤밥 &고급음료,F,150,0,0,0,0,0,-150,2013,8,19,0
grill & fry,2013-08-19,쇠고기야끼니꾸벤또,F,200,0,0,0,0,0,-200,2013,8,19,0
noodle bar,2013-08-19,탄탄멘,F,314,0,0,0,0,0,-314,2013,8,19,0
rice & soup 1,2013-08-20,뚝배기버섯불고기,F,390,0,0,0,0,0,-390,2013,8,20,1
after school,2013-08-20,라면+롤밥 &고급음료,F,155,0,0,0,0,0,-155,2013,8,20,1
noodle bar,2013-08-20,몽골리안치킨면,F,219,0,0,0,0,0,-219,2013,8,20,1
burger&pizza,2013-08-20,케이준치킨버거,F,153,0,0,0,0,0,-153,2013,8,20,1
noodle bar,2013-08-21,바지락칼국수,F,182,0,0,0,0,0,-182,2013,8,21,2
grill & fry,2013-08-21,돈목살스테이크,F,321,0,0,0,0,0,-321,2013,8,21,2
rice & soup 1,2013-08-21,갈비탕,F,514,0,0,0,0,0,-514,2013,8,21,2
after school,2013-08-21,라면+롤밥 &고급음료,F,155,0,0,0,0,0,-155,2013,8,21,2
rice & soup 1,2013-08-22,돼지고기사태떡찜(뚝),F,354,0,0,0,0,0,-354,2013,8,22,3
burger&pizza,2013-08-22,하와이안버거,F,176,0,0,0,0,0,-176,2013,8,22,3
grill & fry,2013-08-22,치즈돈가스,F,327,0,0,0,0,0,-327,2013,8,22,3
after school,2013-08-22,라면+롤밥 &고급음료,F,144,0,0,0,0,0,-144,2013,8,22,3
grill & fry,2013-08-23,추억의도시락,F,211,0,0,0,0,0,-211,2013,8,23,4
after school,2013-08-23,라면+롤밥 &고급음료,F,149,0,0,0,0,0,-149,2013,8,23,4
rice & soup 1,2013-08-23,만두전골(뚝),F,346,0,0,0,0,0,-346,2013,8,23,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
grill & fry,2015-07-20,불고기채소비빔밥,F,188,0,0,23,4,0,-188,2015,7,20,0
after school,2015-07-20,너구리라면,F,114,0,0,27,7,0,-114,2015,7,20,0
burger&pizza,2015-07-20,라자냐,T,159,0,0,47,7,4,-159,2015,7,20,0
take out,2015-07-20,스페셜유부초밥&쇠고기주먹밥,F,137,0,0,0,0,0,-137,2015,7,20,0
noodle bar,2015-07-20,한방돈사태찜,F,105,0,0,20,2,3,-105,2015,7,20,0
rice & soup 1,2015-07-20,(뚝)닭매운찜,F,198,0,0,25,10,5,-198,2015,7,20,0
noodle bar,2015-07-21,닭가슴살채소볶음,F,101,0,0,11,5,3,-101,2015,7,21,1
burger&pizza,2015-07-21,수제베이컨버거,F,128,0,0,34,9,1,-128,2015,7,21,1
rice & soup 1,2015-07-21,(뚝)감자고추장찌개,F,197,0,0,18,16,8,-197,2015,7,21,1
grill & fry,2015-07-21,치킨마요덮밥,F,191,0,0,13,17,17,-191,2015,7,21,1
take out,2015-07-21,장조림컵밥*미니샐러드,F,147,0,0,0,0,0,-147,2015,7,21,1
after school,2015-07-21,숙주라면,F,114,0,0,11,4,2,-114,2015,7,21,1
after school,2015-07-22,짜파게티&계란후라이,F,144,0,0,25,6,2,-144,2015,7,22,2
grill & fry,2015-07-22,고추잡채덮밥,F,203,0,0,36,11,1,-203,2015,7,22,2
burger&pizza,2015-07-22,치킨화지타,F,68,0,0,17,8,0,-68,2015,7,22,2
take out,2015-07-22,케밥,F,139,0,0,0,0,1,-139,2015,7,22,2
rice & soup 1,2015-07-22,뚝배기불고기,F,231,0,0,41,8,1,-231,2015,7,22,2
noodle bar,2015-07-22,임연수카레튀김,F,53,0,0,11,7,4,-53,2015,7,22,2
burger&pizza,2015-07-23,퀘사디아,F,134,0,0,26,10,2,-134,2015,7,23,3
rice & soup 1,2015-07-23,(뚝)유부버섯전골,F,158,0,0,13,11,14,-158,2015,7,23,3
grill & fry,2015-07-23,더덕비빔밥,F,88,0,0,15,3,1,-88,2015,7,23,3
noodle bar,2015-07-23,두부버섯탕수,F,66,0,0,15,5,3,-66,2015,7,23,3
take out,2015-07-23,오므라이스,F,115,0,0,0,0,0,-115,2015,7,23,3
after school,2015-07-23,베이컨마늘라면,F,122,0,0,20,6,1,-122,2015,7,23,3
take out,2015-07-24,스팸구공탄라이스*미니샐러드,F,77,0,0,0,0,0,-77,2015,7,24,4
rice & soup 1,2015-07-24,돼지고기고추장볶음,T,148,0,0,0,0,0,-148,2015,7,24,4
burger&pizza,2015-07-24,어니언버거,F,33,0,0,0,0,0,-33,2015,7,24,4
after school,2015-07-24,삼양라면,F,72,0,0,0,0,0,-72,2015,7,24,4
grill & fry,2015-07-24,스팸김치볶음밥,F,131,0,0,0,0,0,-131,2015,7,24,4
noodle bar,2015-07-24,쇠고기청경채볶음,F,46,0,0,0,0,0,-46,2015,7,24,4

### 정수 색인
기본 정수 색인이 아닌 정수 색인이 부여된 경우 색인 선택의 문제

In [121]:
시리즈=pd.Series([0, 1, 2])

In [122]:
시리즈.ix[0]

0

In [125]:
시리즈2 = pd.Series(['하나', '둘', '셋'], index=[1, 2, 3])

In [126]:
시리즈2

1    하나
2     둘
3     셋
dtype: object

색인이 1이라고 하면, 두 가지 중 갈등상황이 발생할 수 있습니다.
1. 기본 정수 색인 1 즉, 두 번째 원소
2. 직접 부여한 정수 색인 1

In [127]:
시리즈2.ix[1]

'하나'

색인이 부여된 경우에도 위치만을 기준으로 선택하기
-> 기본 색인을 이용한 데이터 추출

In [129]:
시리즈2.iloc[1]
# iloc 을 활용하여 기본 색인을 이용한 데이터 추출

'둘'